# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecorationOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('acquired', models.DateField(default=datetime.date(1872, 1, 1))),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Decoration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('begin_date', models.DateField(default=datetime.date(1872, 1, 1))),
                ('end_date', models.DateField(default=datetime.date(1872, 1, 1))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FunctionaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('begin_date', models.DateField(default=datetime.date(1872, 1, 1))),
                ('end_date', models.DateField(default=datetime.date(1872, 1, 1))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('begin_date', models.DateField(default=datetime.date(1872, 1, 1))),
                ('end_date', models.DateField(default=datetime.date(1872, 1, 1))),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='committees',
            name='committee_type',
        ),
        migrations.RemoveField(
            model_name='committees',
            name='members',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='members',
        ),
        migrations.DeleteModel(
            name='DepartmentTypes',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='members',
        ),
        migrations.RemoveField(
            model_name='memberscommitteesrelation',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='memberscommitteesrelation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberscommitteesrelation',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='membersdepartmentsrelation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='membersdepartmentsrelation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membersgroupsrelation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membersgroupsrelation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberspostsrelation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberspostsrelation',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='members',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_type',
        ),
        migrations.DeleteModel(
            name='Committees',
        ),
        migrations.DeleteModel(
            name='CommitteeTypes',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='MembersCommitteesRelation',
        ),
        migrations.DeleteModel(
            name='MembersDepartmentsRelation',
        ),
        migrations.DeleteModel(
            name='MembersGroupsRelation',
        ),
        migrations.DeleteModel(
            name='MembersPostsRelation',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='PostTypes',
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='grouptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.GroupType'),
        ),
        migrations.AddField(
            model_name='functionary',
            name='functionarytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.FunctionaryType'),
        ),
        migrations.AddField(
            model_name='functionary',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='decorationownership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
