# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='degree_programme',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
