# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-10 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160428_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='degree_programme',
            field=models.CharField(choices=[('UN', 'Okänd'), ('ARTS - Högskolan för konst, design och arkitektur', (('', 'Arkitektur'), ('', 'Bildkonstpedagogik'), ('', 'Design'), ('', 'Dokumentärfilm'), ('', 'Film- och tv-manuskript'), ('', 'Film- och tv-produktion'), ('', 'Film- och tv-scenografi'), ('', 'Filmklippning'), ('', 'Filmljudinspelning och -ljudplanering'), ('', 'Filmning'), ('', 'Filmregi'), ('', 'Grafisk design'), ('', 'Inredningsarkitektur'), ('', 'Kostymdesign'), ('', 'Landskapsarkitektur'), ('', 'Kostymdesign'), ('', 'Landskapsarkitektur'), ('', 'Mode'), ('', 'Teaterscenografi'))), ('BIZ - Handelshögskolan', ('', 'Kauppatieteet')), ('CHEM - Högskolan för kemiteknik', ('', 'Kemi-, bio- och materialteknik')), ('ELEC - Högskolan för elektroteknik', (('', 'Automations- och informationsteknologi'), ('', 'Bioinformationsteknologi'), ('', 'Elektronik och elektroteknik'))), ('ENG - Högskolan för ingenjörsvetenskaper', (('', 'Den byggda miljön'), ('', 'Energi- och miljöteknik'), ('', 'Maskin- och byggnadsteknik'))), ('SCI - Högskolan för teknikvetenskaper', (('', 'Datateknik'), ('', 'Informationsnätverk'), ('', 'Produktionsekonomi'), ('', 'Teknisk fysik och matematik')))], default='UN', max_length=256),
        ),
        migrations.AddField(
            model_name='member',
            name='enrolment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna'), ('UN', 'Okänd')], default='UN', max_length=2),
        ),
    ]
