# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_stalm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set([('member', 'group')]),
        ),
    ]
