# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170110_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='degree_programme',
            field=models.CharField(choices=[('UN', 'Okänd'), ('ARTS - Högskolan för konst, design och arkitektur', (('ARK', 'Arkitektur'), ('BP', 'Bildkonstpedagogik'), ('DS', 'Design'), ('DK', 'Dokumentärfilm'), ('FM', 'Film- och tv-manuskript'), ('FP', 'Film- och tv-produktion'), ('FS', 'Film- och tv-scenografi'), ('FK', 'Filmklippning'), ('FL', 'Filmljudinspelning och -ljudplanering'), ('FI', 'Filmning'), ('FR', 'Filmregi'), ('GD', 'Grafisk design'), ('IA', 'Inredningsarkitektur'), ('KD', 'Kostymdesign'), ('LA', 'Landskapsarkitektur'), ('MD', 'Mode'), ('TS', 'Teaterscenografi'))), ('BIZ - Handelshögskolan', ('KT', 'Kauppatieteet')), ('CHEM - Högskolan för kemiteknik', ('KB', 'Kemi-, bio- och materialteknik')), ('ELEC - Högskolan för elektroteknik', (('AI', 'Automations- och informationsteknologi'), ('BI', 'Bioinformationsteknologi'), ('EL', 'Elektronik och elektroteknik'))), ('ENG - Högskolan för ingenjörsvetenskaper', (('BM', 'Den byggda miljön'), ('EM', 'Energi- och miljöteknik'), ('MB', 'Maskin- och byggnadsteknik'))), ('SCI - Högskolan för teknikvetenskaper', (('DT', 'Datateknik'), ('IN', 'Informationsnätverk'), ('PE', 'Produktionsekonomi'), ('TF', 'Teknisk fysik och matematik')))], default='UN', max_length=256),
        ),
    ]
