# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170418_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ldap_username', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('bill_code', models.CharField(blank=True, default='', max_length=6, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='useraccountdata',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
