# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20170502_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountdata',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='bill_code',
            field=models.CharField(editable=False, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='UserAccountData',
        ),
    ]
