# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20170202_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='stalm',
            field=models.BooleanField(default=False),
        ),
    ]
