# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20170214_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AlterField(
            model_name='decorationownership',
            name='acquired',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='begin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='group',
            name='begin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('UN', 'Okänd'), ('M', 'Man'), ('F', 'Kvinna')], default='UN', max_length=2),
        ),
    ]
