# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20170301_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='begin_date',
            field=models.DateField(default=members.models.getFirstDayOfCurrentYear),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='end_date',
            field=models.DateField(default=members.models.getLastDayOfCurrentYear),
        ),
        migrations.AlterField(
            model_name='group',
            name='begin_date',
            field=models.DateField(default=members.models.getFirstDayOfCurrentYear),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(default=members.models.getLastDayOfCurrentYear),
        ),
    ]
