# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-22 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20170816_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='functionary',
            unique_together=set([('member', 'functionarytype', 'begin_date', 'end_date')]),
        ),
    ]
