# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20170906_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
