# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20170925_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(editable=False, max_length=32, null=True, unique=True),
        ),
    ]
