DEGREE_PROGRAMME_CHOICES = (
    'Arkitektur',
    'Bildkonstpedagogik',
    'Design',
    'Dokumentärfilm',
    'Film- och tv-manuskript',
    'Film- och tv-produktion',
    'Film- och tv-scenografi',
    'Filmklippning',
    'Filmljudinspelning och -ljudplanering',
    'Filmning',
    'Filmregi',
    'Grafisk design',
    'Inredningsarkitektur',
    'Kostymdesign',
    'Landskapsarkitektur',
    'Mode',
    'Teaterscenografi',
    'Kauppatieteet',
    'Kemi-, bio- och materialteknik',
    'Automations- och informationsteknologi',
    'Bioinformationsteknologi',
    'Elektronik och elektroteknik',
    'Den byggda miljön',
    'Energi- och miljöteknik',
    'Maskin- och byggnadsteknik',
    'Datateknik',
    'Informationsnätverk',
    'Produktionsekonomi',
    'Teknisk fysik och matematik',
)
